<h1>MINI PROJET <font color='red'>Traitement de Données avec Python - Pandas </font></h1>

### ZONGO Celse Darius Pegdwende

Le but de cet exercice est d'extraire un sous-ensemble de données à partir d'une base de données
existante.
Supposons que vous ayez besoin de réaliser une application qui prend en entrée, des noms de lieux du Burkina Faso, avec des informations telles que la latitude/longitude.
Pour ce faire, nous décidons d'extraire ces informations à partir du server de référencement géoname (http://www.geonames.org/). Vous allez procéder de la façon suivante :
1. Exporter la base de données qui recense les informations sur le Burkina Faso (https://download.geonames.org/export/dump/).
◦ Pour ce faire, reférez-vous au Readme, décrit à la fin de la page pour identifier le
code iso correspondant à celui du Burkina Faso
2. Télécharger le fichier zip correspondant
3. Appliquer les opérations de prétraitement et filtres nécessaires à ce fichier, pour ne garder que les colonnes correspondantes :
◦ Identifiants, Noms de lieux, latitudes, longitudes
◦ Renommez les avec les noms suivants : 'ID', 'location_name', 'lat', 'long'
◦ Sauvegarder ces données dans un fichier CSV, nommez-le burkina_location.csv
4. Opérations sur le fichier CSV burkina_location.csv.
◦ Extraire les données contenant le nom 'gounghin', enregistrez-le sous le fichier gounghin.csv
◦ Extraire la sous-partie de la base de données (fichier burkina_location.csv), dont les premières lettres des noms de lieux sont compris entre 'A' et 'P' (ordre alphabétique).
◦ Identifiez respectivement, la latitude, la longitude minimale et les noms de lieux correspondants dans le fichier burkina_location.csv.
◦ Quels sont les lieux dont les coordonnées sont comprises entre (lat >= 11 et lon <= 0.5)
5. Sorties Excel
Rodrique K. Mini Projet Master FD&IA Uvbf 2021
À partir des extractions de l'étape 4 :
◦ Créer un fichier Excel et nommer le : mini_projet
◦ Créer une feuille dans ce fichier, du nom gounghin et enregistrer les données contenant le nom ‘gounghin’ obtenues dans 4.1
◦ Créer une second feuille dans ce même fichier, du nom A_to_P et enregistrer les données de 4.2

<h2> <font color='green'>1. & 2 export des donnees effectues </font></h2>

<h2> <font color='green'> 3. PRETRAITREMENT </font></h2>

3. Appliquer les opérations de prétraitement et filtres nécessaires à ce fichier, pour ne garder que les colonnes correspondantes :
◦ Identifiants, Noms de lieux, latitudes, longitudes
◦ Renommez les avec les noms suivants : 'ID', 'location_name', 'lat', 'long'
◦ Sauvegarder ces données dans un fichier CSV, nommez-le burkina_location.csv

### <font color='blue'> Import </font>

In [1]:
import pandas as pd

data= pd.read_csv("BF/BF.txt", sep="\t", header=None) 
##on met le nom original des colonnes
data.columns=["geonameid", "name" ,"asciiname" ,"alternatenames","latitude" ,"longitude" ,"feature class","feature code" ,"country code","cc2","admin1 code" ,"admin2 code" ,"admin3 code","admin4 code","population","elevation","dem" ,"timezone","modification date"]
data

,geonameid,name,asciiname,alternatenames,latitude,longitude,feature class,feature code,country code,cc2,admin1 code,admin2 code,admin3 code,admin4 code,population,elevation,dem,timezone,modification date
0,2353158,Zyonguen,Zyonguen,NaN,12.36667,-0.45000,P,PPL,BF,NaN,04,NaN,NaN,NaN,0,NaN,293,Africa/Ouagadougou,2012-06-05
1,2353159,Zyiliwèlè,Zyiliwele,NaN,12.38333,-2.73333,P,PPL,BF,NaN,06,NaN,NaN,NaN,0,NaN,277,Africa/Ouagadougou,2012-06-05
2,2353160,Zyanko,Zyanko,NaN,12.78333,-0.41667,P,PPL,BF,NaN,05,NaN,NaN,NaN,0,NaN,301,Africa/Ouagadougou,2012-06-05
3,2353161,Zouta,Zouta,NaN,13.14908,-1.28197,P,PPL,BF,NaN,05,70.0,NaN,NaN,0,NaN,306,Africa/Ouagadougou,2010-07-31
4,2353162,Zourtenga,Zourtenga,NaN,12.95741,-1.28745,P,PPL,BF,NaN,05,NaN,NaN,NaN,0,NaN,290,Africa/Ouagadougou,2018-09-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11292,12358656,Timambari,Timambari,NaN,11.84209,1.67023,P,PPL,BF,NaN,08,42.0,NaN,NaN,0,NaN,298,Africa/Ouagadougou,2021-10-23
11293,12358657,Nagbingou,Nagbingou,NaN,13.55244,-0.46760,P,PPL,BF,NaN,05,64.0,NaN,NaN,0,NaN,275,Africa/Ouagadougou,2021-10-23
11294,12358665,Niamango,Niamango,NaN,9.82967,-4.33708,P,PPL,BF,NaN,02,55.0,NaN,NaN,0,NaN,299,Africa/Ouagadougou,2021-10-24
11295,12358676,Sella,Sella,NaN,14.35699,0.28666,P,PPL,BF,NaN,12,71.0,NaN,NaN,0,NaN,292,Africa/Niamey,2021-10-25
11296,12358677,Kiefaye,Kiefaye,NaN,13.78260,-1.58790,P,PPL,BF,NaN,05,15.0,NaN,NaN,0,NaN,320,Africa/Ouagadougou,2021-10-25

###  <font color='blue'> Filtrage de donnees et reindexage des colonnes selectionnees </font>

In [2]:
#on selectionne les colonnes qui nous interressent
burkina= data[["geonameid","name","latitude","longitude"]]

# on renomme les colonnes
burkina.columns=["ID", 'location_name', 'lat', 'long']
burkina

             ID location_name       lat     long
0       2353158      Zyonguen  12.36667 -0.45000
1       2353159     Zyiliwèlè  12.38333 -2.73333
2       2353160        Zyanko  12.78333 -0.41667
3       2353161         Zouta  13.14908 -1.28197
4       2353162     Zourtenga  12.95741 -1.28745
...         ...           ...       ...      ...
11292  12358656     Timambari  11.84209  1.67023
11293  12358657     Nagbingou  13.55244 -0.46760
11294  12358665      Niamango   9.82967 -4.33708
11295  12358676         Sella  14.35699  0.28666
11296  12358677       Kiefaye  13.78260 -1.58790

[11297 rows x 4 columns]

### <font color='blue'>  Sauvegarde des donnees dans le dossier output </font>

In [3]:
#on enregistre la selectionne dans le dossier output
burkina.to_csv('output/burkina_location.csv', index=False)

<h2> <font color='green'> 4. Opérations sur le fichier CSV burkina_location.csv </font></h2>

4. Opérations sur le fichier CSV burkina_location.csv.
◦ Extraire les données contenant le nom 'gounghin', enregistrez-le sous le fichier gounghin.csv
◦ Extraire la sous-partie de la base de données (fichier burkina_location.csv), dont les premières lettres des noms de lieux sont compris entre 'A' et 'P' (ordre alphabétique).
◦ Identifiez respectivement, la latitude, la longitude minimale et les noms de lieux correspondants dans le fichier burkina_location.csv.
◦ Quels sont les lieux dont les coordonnées sont comprises entre (lat >= 11 et lon <= 0.5)

### <font color='blue'> Extraction des donnnes contenant "gounghin" </font>

In [4]:
#on met la colonne en minuscule afin de verifier la presence de gounghin
burkina_lower=burkina['location_name'].str.lower()
gounghin_validator=burkina_lower.str.contains('gounghin')

#on affiche les donnees qui contiennent "gounghin"
burkina[gounghin_validator]

             ID                  location_name       lat     long
147     2353306                       Gounghin  12.06677 -1.42134
7256    2360473                       Gounghin  12.62488 -1.36398
10227   2570204                       Gounghin  12.31436 -1.37900
10688  10342749                       Gounghin  12.06667 -0.15000
10701  10629032             BICIAB // Gounghin  12.35921 -1.54273
10760  11257296            Gounghin Department  12.06671 -0.15484
10787  11900526                  Gounghin Nord  12.36120 -1.55055
10788  11900528  Zone Industrielle de Gounghin  12.36631 -1.54137
10794  11900619                   Gounghin Sud  12.35298 -1.54342
10808  11900680                       Gounghin  12.35895 -1.54442

### <font color='blue'> Enregistrement de la selection </font>

In [5]:
burkina_location =pd.read_csv("output/burkina_location.csv") 
#enregistrement de la selection dans le dossier output
burkina_location[gounghin_validator].to_csv('output/gounghin.csv', index=False)

### <font color='blue'> Selection des localites dont les noms commencent entre A et P <font>

In [6]:
#on recupere la liste des localites dont le nom commence par ordre alphabetique entre A et P
lis_A_to_P=burkina_location[burkina_location['location_name'].str.startswith(("A","B","C","D","E","F","G","H","I","J","K","L","M","N","P"))]

In [7]:
## ordonner par ordre alphabetique 
list_A_to_P= lis_A_to_P.sort_values('location_name')
list_A_to_P

             ID location_name       lat     long
10590   6913771        Abanda  15.06808 -0.59805
10013   2363251        Abanga  13.32429  0.31151
11035  11980339        Abassi  12.27728 -1.13662
10551   6874881         Abaye  13.44080 -3.90190
10011   2363249          Abra  13.09140 -1.34752
...         ...           ...       ...      ...
10078   2570015       Pézinga  12.05298 -1.47002
3468    2356655            Pê  11.30000 -3.53333
3268    2356453            Pô  12.30000 -2.61667
3269    2356454            Pô  11.16972 -1.14500
10360   6296406    Pô Airport  11.17854 -1.14498

[7446 rows x 4 columns]

### <font color='blue'>  Presentation de la localite avec la latitude minimale </font>

In [8]:
#on recupere l'index de la colonne ayant la lattitude minimal que l'on place dans un iloc
min_lat= burkina_location.iloc[burkina_location["lat"].idxmin()]
min_lat

ID                   12224995
location_name    Fadio-Mèpèhn
lat                    9.4295
long                  -2.7775
Name: 11149, dtype: object

### <font color='blue'> Presentation de la localite avec la longitude minimale </font>

In [9]:
min_long= burkina_location.iloc[burkina_location["long"].idxmin()]
min_long

ID                2354426
location_name    Tinobolé
lat                 10.75
long             -5.48333
Name: 1255, dtype: object

### <font color='blue'>  Listes des localites dont les coordonnnees respectent les conditions </font>

In [10]:
lat_validator= burkina_location['lat']>=11
long_validator= burkina_location['long']<=0.5

list_coordonnee= burkina_location[lat_validator & long_validator]
list_coordonnee

             ID location_name       lat     long
0       2353158      Zyonguen  12.36667 -0.45000
1       2353159     Zyiliwèlè  12.38333 -2.73333
2       2353160        Zyanko  12.78333 -0.41667
3       2353161         Zouta  13.14908 -1.28197
4       2353162     Zourtenga  12.95741 -1.28745
...         ...           ...       ...      ...
11288  12358467          Katé  14.13461 -0.81244
11290  12358654      Koulholé  13.43898 -1.16817
11293  12358657     Nagbingou  13.55244 -0.46760
11295  12358676         Sella  14.35699  0.28666
11296  12358677       Kiefaye  13.78260 -1.58790

[9026 rows x 4 columns]

<h2> <font color='green'>  5. Sorties Excel </font></h2>

5. Sorties Excel
Rodrique K. Mini Projet Master FD&IA Uvbf 2021
À partir des extractions de l'étape 4 :
◦ Créer un fichier Excel et nommer le : mini_projet
◦ Créer une feuille dans ce fichier, du nom gounghin et enregistrer les données contenant le nom ‘gounghin’ obtenues dans 4.1
◦ Créer une second feuille dans ce même fichier, du nom A_to_P et enregistrer les données de 4.2

In [11]:
## ecriture des 2 feuilles dans le fichier excel

with pd.ExcelWriter('output/mini_projet.xlsx') as writer:  
    burkina_location[gounghin_validator].to_excel(writer, sheet_name='gounghin', index=False)
    list_A_to_P.to_excel(writer, sheet_name='A_to_P', index=False)